version: "3"
services:
  led_driver:
    command: --privileged
    image: led_driver:latest
    # build: 
    #   context: ./led_driver
    restart: always
    volumes:
      - /var/run/:/lannootree/dev
      - /dev/mem:/dev/mem
      - /dev/vcio:/dev/vcio
      - /dev/gpiomem:/dev/gpiomem
      - /proc/cpuinfo:/proc/cpuinfo

  controller:
    build:
      context: ./controller
    restart: always
    volumes:
      - ./config.json:/config.json
    # depends_on:
    #   - led_driver
