version: "3"
services:
  led-driver:
    image: led-driver:latest
    build: 
      context: ./led_driver
    privileged: true
    restart: always
    volumes:
      - ${PWD}/config.json:/lannootree/config.json
      - /var/run/:/lannootree/dev
      - /dev/mem:/dev/mem
      - /dev/vcio:/dev/vcio
      - /dev/gpiomem:/dev/gpiomem
      - /proc/cpuinfo:/proc/cpuinfo

  led-client:
    image: led-client:latest
    build:
      context: ./led-client
    privileged: true
    restart: always
    env_file:
      - .env
    volumes:
      - ${PWD}/config.json:/config.json
      - ${PWD}/ca_crt/ca.crt:/app/ca.crt
      - /var/run/:/var/run/
