version: "3"
services:
  cert_downloader:
    image: curlimages/curl
    command: "curl https://lannootree.devbitapp.be/ca.crt --output /ca.crt/ca.crt"
    user: 1001:1001
    volumes:
      - ./ca.crt:/ca.crt

  led_driver:
    command: --privileged
    image: led_driver:latest
    # build: 
    #   context: ./led_driver
    restart: always
    volumes:
      - /var/run/:/lannootree/dev
      - /dev/mem:/dev/mem
      - /dev/vcio:/dev/vcio
      - /dev/gpiomem:/dev/gpiomem
      - /proc/cpuinfo:/proc/cpuinfo

  controller:
    build:
      context: ./controller 
    env_file:
      - .env
    restart: always
    volumes:
      - ./config.json:/config.json
      - ./ca_crt/ca.crt:/app/ca.crt
