version: "3"
services:
  led_driver:
    image: led-driver:latest
    build: 
      context: ./led_driver
    privileged: true
    restart: always
    volumes:
      - ./config.json=/lannootree/config.json
      - /var/run/:/lannootree/dev
      - /dev/mem:/dev/mem
      - /dev/vcio:/dev/vcio
      - /dev/gpiomem:/dev/gpiomem
      - /proc/cpuinfo:/proc/cpuinfo

  controller:
    image: led-client:latest
    build:
      context: ./led-client
    env_file:
      - .env
    restart: always
    volumes:
      - ./config.json:/config.json
      - ./ca_crt/ca.crt:/app/ca.crt
