version: "3"
services:
  led_driver:
    build: 
      context: ./led_driver
    restart: unless-stopped
    volumes:
      - /var/run/:/lannootree/dev

  controller:
    build:
      context: ./controller
    restart: unless-stopped
    depends_on:
      - led_driver
